## Pandas Workbook

students = [
    ["Aarav", 85, 78, 92],
    ["Riya", 91, 88, 95],
    ["Kabir", 72, 69, 80],
]

In [ ]:
# code here
students = [
    ["Aarav", 85, 78, 92],
    ["Riya", 91 ,88 , 95],
    ["Kabir", 72, 69, 80],
]
print(students)

[['Aarav', 85, 78, 92], ['Riya', 91, 95], ['Kabir', 72, 69, 80]]

### can you answer these question based on the code above ?
What does 85 represent?

How do I get all the Maths marks?

How do I get Riya's marks?

What if I add 20 more students?

What if one student has a missing mark?

What if I want to filter students with average > 80?

| Name  | Maths | Physics | Python |
| ----- | ----: | ------: | -----: |
| Aarav |    85 |      78 |     92 |
| Riya  |    91 |      88 |     95 |
| Kabir |    72 |      69 |     80 |

## what does pandas give us?

**Series  →  one column**

**DataFrame →  complete table**

## Creating a DataFrame

A Pandas DataFrame is a two-dimensional labelled data structure.

Let's create one from a dictionary.

############################################

import pandas as pd

In [9]:
import pandas as pd

students = [
    ["Alice", 21, "Pune", 85],
    ["Bob", 22, "Mumbai", 91],
    ["Charlie", 20, "Pune", 78]
]

df = pd.DataFrame(
    students,
    columns=["Name", "Age", "City", "Score"]
)

df

In [11]:
# code here
students = [
    ["Alice", 21, "Pune", 85],
    ["Bob", 22, "Mumbai", 91],
    ["Charlie", 20, "Pune", 78]
]
print(students)

df = pd.DataFrame(
    students,
    columns=["Name", "Age", "City", "Score"]
)
print('\n')
print(df)

[['Alice', 21, 'Pune', 85], ['Bob', 22, 'Mumbai', 91], ['Charlie', 20, 'Pune', 78]]


      Name  Age    City  Score
0    Alice   21    Pune     85
1      Bob   22  Mumbai     91
2  Charlie   20    Pune     78

## Understanding a DataFrame

Before we start manipulating data, let's understand the basic structure of a DataFrame.

A DataFrame consists of:

- **Rows** — individual observations or records
- **Columns** — variables or attributes
- **Index** — labels used to identify rows

For our DataFrame:

| Index | Name | Age | City | Score |
|------:|------|----:|------|------:|
| 0 | Alice | 21 | Pune | 85 |
| 1 | Bob | 22 | Mumbai | 91 |
| 2 | Charlie | 20 | Pune | 78 |

The index is automatically created by Pandas when we create the DataFrame.

Let's inspect some basic properties of our DataFrame.

### Try this with the df you have created and see what all output you get?

df.head()

df.tail()

df.shape

df.columns

df.index

df.dtypes

df.info()

df.describe()

In [ ]:
#code here

## Try this with the df you have created and see what all output you get?

#df.head()

# df.tail(2)

# df.shape

# df.columns

# df.index

#df.dtypes

# df.info()

# df.describe()

        Age      Score
count   3.0   3.000000
mean   21.0  84.666667
std     1.0   6.506407
min    20.0  78.000000
25%    20.5  81.500000
50%    21.0  85.000000
75%    21.5  88.000000
max    22.0  91.000000

## Selecting Columns

A DataFrame contains multiple columns, but often we are interested in only a few of them.

For example, suppose we only want to look at the students' names.

We can select a column using its column name:

```python


df["Name"]

In [34]:
#code here
df["Name"]

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

### What did we get?

Notice that the result is **not another DataFrame**.

It is a Pandas **Series**.

A `Series` is a one-dimensional labelled data structure in Pandas.

You can think of it as a **single column** of a DataFrame.

### DataFrame vs Series

The relationship can be visualised like this:

```text
DataFrame
┌───────┬─────────┬─────┬────────┬───────┐
│ Index │ Name    │ Age │ City   │ Score │
├───────┼─────────┼─────┼────────┼───────┤
│   0   │ Alice   │ 21  │ Pune   │  85   │
│   1   │ Bob     │ 22  │ Mumbai │  91   │
│   2   │ Charlie │ 20  │ Pune   │  78   │
└───────┴─────────┴─────┴────────┴───────┘

              ↓ select one column

Series
┌───────┬─────────┐
│ Index │ Name    │
├───────┼─────────┤
│   0   │ Alice   │
│   1   │ Bob     │
│   2   │ Charlie │
└───────┴─────────┘


### Markdown cell

```markdown
## Selecting Multiple Columns

What if we want both `Name` and `Score`?

We can pass a **list of column names** inside the square brackets:

```python
df[["Name", "Score"]]

In [40]:
#code here

#df[["Name", "Score"]]

print(df["City"])
print()
print(df["Age"])
print()
print(df[["Name", "City"]])

0      Pune
1    Mumbai
2      Pune
Name: City, dtype: str

0    21
1    22
2    20
Name: Age, dtype: int64

      Name    City
0    Alice    Pune
1      Bob  Mumbai
2  Charlie    Pune

### 🧠 Try It Yourself

Using `df`, select:

1. Only the `City` column.
2. Only the `Age` column.
3. The `Name` and `City` columns.
4. The `Name`, `Age`, and `Score` columns.

Then check the type of the result for a single column and for multiple columns.

**Question:** Why do you think Pandas returns a Series when selecting one column but a DataFrame when selecting multiple columns?

########################################################################

## Selecting Rows

So far, we have learned how to select columns.

But what if we want to select specific **rows**?

Pandas provides two important tools for selecting rows:

- `iloc` — select using the **position** of the row
- `loc` — select using the **label** of the row

Let's start with `iloc`.

### `iloc` — Integer Position Based Selection

`iloc` stands for **integer-location**.

It allows us to select rows and columns based on their **numerical position**.

Remember that our DataFrame has the following row positions:

| Position | Index | Name |
|---:|---:|---|
| 0 | 0 | Alice |
| 1 | 1 | Bob |
| 2 | 2 | Charlie |

To select the first row:


df.iloc[0]

In [45]:
#code here

df.iloc[1]

Name        Bob
Age          22
City     Mumbai
Score        91
Name: 1, dtype: object

The result is a **Series** containing the values from that row.

Just like selecting a single column:

```python
df["Name"]

#### Selecting Multiple Rows

df.iloc[0:2]

In [48]:
#code here

df.iloc[0:2]

    Name  Age    City  Score
0  Alice   21    Pune     85
1    Bob   22  Mumbai     91

### Selecting a Specific Row and Column

`iloc` can also be used to select both rows and columns.

The general syntax is:

```python
df.iloc[row, column]

df.iloc[0, 1]

In [53]:
#code here

df.iloc[row, column]

NameError: name 'row' is not defined

We can also select a range of rows and columns:

```python
df.iloc[0:2, 0:2]

In [ ]:
#code here 
df.iloc[0:2, 0:2]

#slect second column
df.iloc[:, 1]

#selcet last row
df.iloc[-1]

#selct 1st 2 rows and 1st 2 rows
df.iloc[0:2, 0:2]


#slect name age of 1st 2 rows
df.iloc[0:2, [0, 1]]

    Name  Age
0  Alice   21
1    Bob   22

### 🧠 Try It Yourself

Using `iloc`, try to:

1. Select the second row.
2. Select the last row.
3. Select the first two rows.
4. Select the `Name` and `Age` columns of the first two rows.
5. Select the value `91` directly using its row and column position.

**Hint:** Remember that indexing starts from `0`.

## `loc` — Label-Based Selection

`loc` is used to select data based on **labels**.

The important distinction is:

> `iloc` → **position**  
> `loc` → **label**

So far, our DataFrame has the default index:

| Index | Name | Age | City | Score |
|------:|------|----:|------|------:|
| 0 | Alice | 21 | Pune | 85 |
| 1 | Bob | 22 | Mumbai | 91 |
| 2 | Charlie | 20 | Pune | 78 |

Here, the index values (`0`, `1`, `2`) are also labels.

For example:


```python
df.loc[0]

In [62]:
#code here
df.loc[0]

Name     Alice
Age         21
City      Pune
Score       85
Name: 0, dtype: object

### `loc` vs `iloc`

With our current DataFrame, these may appear to do the same thing:

```python
df.loc[0]
df.iloc[0]

In [63]:
df.loc[0]
df.iloc[0]

Name     Alice
Age         21
City      Pune
Score       85
Name: 0, dtype: object


### Code cell

```python
df_custom = df.copy()

df_custom.index = ["student_A", "student_B", "student_C"]

df_custom

In [65]:

### Code cell


df_custom = df.copy()

df_custom.index = ["student_A", "student_B", "student_C"]

df_custom

              Name  Age    City  Score
student_A    Alice   21    Pune     85
student_B      Bob   22  Mumbai     91
student_C  Charlie   20    Pune     78

Now our DataFrame looks like:

| Index | Name | Age | City | Score |
|---|---|---:|---|---:|
| student_A | Alice | 21 | Pune | 85 |
| student_B | Bob | 22 | Mumbai | 91 |
| student_C | Charlie | 20 | Pune | 78 |

Now let's select Bob.

Using `loc`, we can directly use his row label:

```python
df_custom.loc["student_B"]

In [66]:
#code here

df_custom.loc["student_B"]

Name        Bob
Age          22
City     Mumbai
Score        91
Name: student_B, dtype: object

But `iloc` still works with the **position**:

```python
df_custom.iloc[1]

In [ ]:
#code here


df_custom.iloc[1]

Name        Bob
Age          22
City     Mumbai
Score        91
Name: student_B, dtype: object

iloc → position

        ↓
        1st / 2nd / 3rd ...

loc  → label

        ↓
        student_A / student_B / student_C


### Markdown cell

```markdown
## Selecting Rows and Columns with `loc`

Just like `iloc`, `loc` can select both rows and columns.

The general syntax is:

```python
#df.loc[row_label, column_label]
df_custom.loc["student_B", "Score"]

In [72]:
#code here


df_custom.loc["student_B", "Score"]

np.int64(91)

We can also select multiple columns:

```python
df_custom.loc["student_B", ["Name", "City", "Score"]]

In [73]:
#code here


df_custom.loc["student_B", ["Name", "City", "Score"]]

Name        Bob
City     Mumbai
Score        91
Name: student_B, dtype: object

### Selecting Multiple Rows with `loc`

We can provide a list of row labels:

```python
df_custom.loc[["student_A", "student_C"]]

In [74]:

df_custom.loc[["student_A", "student_C"]]

              Name  Age  City  Score
student_A    Alice   21  Pune     85
student_C  Charlie   20  Pune     78

### 🧠 Try It Yourself

Using `df_custom` and `loc`, try to:

1. Select `student_A`.
2. Select the `City` of `student_C`.
3. Select the `Name` and `Score` of `student_B`.
4. Select `student_A` and `student_C`.
5. Select all rows from `student_A` through `student_B`, including both.
6. Select the `Name` and `Score` columns for `student_A` and `student_C`.

### Remember

```text
iloc → integer position
loc  → label

In [ ]:


# 1. Select student_A.
df_custom.loc["student_A"]

# 2. Select the City of student_C.
df_custom.loc["student_C", "City"]

# 3. Select the Name and Score of student_B.
df_custom.loc["student_B", ["Name", "Score"]]

# 4. Select student_A and student_C.
df_custom.loc[["student_A", "student_C"]]

# 5. Select all rows from student_A through student_B, including both.
df_custom.loc["student_A":"student_B"]

# 6. Select the Name and Score columns for student_A and student_C.
df_custom.loc[["student_A", "student_C"], ["Name", "Score"]]

              Name  Score
student_A    Alice     85
student_C  Charlie     78