### Why do we need filtering?

Suppose our DataFrame contains hundreds or thousands of rows.

We don't always want the entire DataFrame.

Instead, we may want to ask questions such as:

"Show me only the students whose Python marks are greater than 80."

We have already seen Boolean conditions in Python:

In [1]:
import pandas as pd

In [2]:
# code here
# Pandas way - much cleaner and more intuitive!
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Python': [85, 92, 78, 90],
    'Maths': [99, 85, 88, 50],
    'Chemistry' : [90, 65, 75, 80],
    'Physics' : [85, 65, 87, 33],
    'Department' : ['SCMS', 'SCMS', 'CS', 'Physics']
})


df

      Name  Python  Maths  Chemistry  Physics Department
0    Alice      85     99         90       85       SCMS
1      Bob      92     85         65       65       SCMS
2  Charlie      78     88         75       87         CS
3    Diana      90     50         80       33    Physics

Try these line below and try to retrive the values from the Physics column where the score is grater than 80

```python
df["Physics"] >80

df.iloc[:,4]

df.loc[:,'Physics'] 

Which rows do you expect to be True?

In [3]:
#code here

df["Physics"] >80

df.iloc[:,4]

df.loc[:,'Physics']

0    85
1    65
2    87
3    33
Name: Physics, dtype: int64

Now you can apply this boolean mask to the data Frame created to get the filterd data

```python 
mask = df["Physics"] >80
print(mask )
df[mask]

In [4]:
#code here

mask = df["Physics"] >80
print(mask )
df[mask]

0     True
1    False
2     True
3    False
Name: Physics, dtype: bool

      Name  Python  Maths  Chemistry  Physics Department
0    Alice      85     99         90       85       SCMS
2  Charlie      78     88         75       87         CS

Try the following and notice the same logic above is being implemented directly in the df
```python
df[df["Python"] > 80]

In [5]:
# code here

df[df["Python"] > 80]

    Name  Python  Maths  Chemistry  Physics Department
0  Alice      85     99         90       85       SCMS
1    Bob      92     85         65       65       SCMS
3  Diana      90     50         80       33    Physics

<span style="color: cyan;">@ Think</span>

will the following line give an error ? 
```python 
df[df["Python"] > 100]

In [6]:
#code here
df[df["Python"] > 100]

Empty DataFrame
Columns: [Name, Python, Maths, Chemistry, Physics, Department]
Index: []

### Combining Conditions
Real questions are often more complicated.

For example:

Find students who scored more than 80 in both Maths and Python.

In normal Python, we might think about using:
> and

But Pandas works differently when comparing an entire Series.

For element-by-element logical operations, we use:

| Operation | Pandas operator |   |
| --------- | --------------- | - |
| AND       | `&`             |   |
| OR        | l           |   |
| NOT       | `~`             |   |


When combining conditions, **put each condition inside parentheses.**

```python 
df[(df['Physics']>80) & (df['Maths']>84)]
df[(df['Physics']>80) | (df['Maths']>84)]
df[~(df['Physics']>80)]

In [7]:
#code here



df[(df['Physics']>80) & (df['Maths']>84)]
df[(df['Physics']>80) | (df['Maths']>84)]
df[~(df['Physics']>80)]

    Name  Python  Maths  Chemistry  Physics Department
1    Bob      92     85         65       65       SCMS
3  Diana      90     50         80       33    Physics

### Filtering with isin()

Sometimes we don't want to write a numerical condition.

Suppose we want students from specific departments: Physics

We could write multiple conditions, but Pandas provides a convenient method:

>isin()

```python
df['Sports'] = ['yes','no','yes','yes']
print(df)
df['Sports'].isin(['yes'])

or
df['Physics'].isin([65,85])

In [9]:
#code here


df['Sports'] = ['yes','no','yes','yes']
print(df)
df['Sports'].isin(['yes'])


df['Physics'].isin([65,85])

      Name  Python  Maths  Chemistry  Physics Department Sports
0    Alice      85     99         90       85       SCMS    yes
1      Bob      92     85         65       65       SCMS     no
2  Charlie      78     88         75       87         CS    yes
3    Diana      90     50         80       33    Physics    yes

0     True
1     True
2    False
3    False
Name: Physics, dtype: bool

### Filtering a Range with between()

Another common question is:

"Give me students whose Python marks are between 80 and 95."

we could write 
>(df["Python"] >= 80) & (df["Python"] <= 95)

But Pandas also provides us

>between()

```python
df["Python"].between(80, 95)
df[df["Python"].between(80, 95)]

In [10]:
#code here

df["Python"].between(80, 95)
df[df["Python"].between(80, 95)]

    Name  Python  Maths  Chemistry  Physics Department Sports
0  Alice      85     99         90       85       SCMS    yes
1    Bob      92     85         65       65       SCMS     no
3  Diana      90     50         80       33    Physics    yes

### Creating New Columns

So far, we've mostly asked questions about existing data.

Now let's create new information from our existing columns.

Suppose we want to calculate each student's average marks.

We already know how to perform arithmetic in Python and NumPy.

We can apply the same idea directly to Pandas columns.

```python 
df["Average"] = (
    df["Maths"] +
    df["Physics"] +
    df["Python"]
) / 3

df

In [11]:
#code here


df["Average"] = (
    df["Maths"] +
    df["Physics"] +
    df["Python"]
) / 3

df

      Name  Python  Maths  Chemistry  Physics Department Sports    Average
0    Alice      85     99         90       85       SCMS    yes  89.666667
1      Bob      92     85         65       65       SCMS     no  80.666667
2  Charlie      78     88         75       87         CS    yes  84.333333
3    Diana      90     50         80       33    Physics    yes  57.666667

<span style="color:cyan">Important idea</span>


df["Maths"] + df["Physics"]

doesn't require a loop.

Pandas performs the operation across the corresponding values.

This should look familiar from our NumPy work:

Vectorised operations

### Inspecting Unique Values

For example:

What departments are present in our dataset?

We can use:

> unique()

```python
df["Department"].unique()

sometime we only need number of unique values 

df["Department"].nunique()

In [13]:
#code here

df["Department"].unique()



df["Department"].nunique()

3

### Counting Categories with value_counts()

Suppose we want to know:

How many students belong to each department?

We could write loops and manually count them.

Pandas provides:

>value_count()

```python 
df['Department'].value_counts()

In [14]:
#code here

df['Department'].value_counts()

Department
SCMS       2
CS         1
Physics    1
Name: count, dtype: int64

### <span style='color:green'>To do</span>
Solve the following 4 tasks with the modules learned above 
1. Find all teh students with less than average marks for each subject
2. Get the list of students who have scored more than 80 and are in SCMS
3. Add a new column in which all the student scoring more than 70 marks pass and other fail (use between())
4. list all teh student passed

In [15]:
# DataFrame
df = pd.DataFrame({
    'Name': ['Vedant', 'Aditya', 'Prapti', 'Saily'],
    'Python': [85, 92, 78, 90],
    'Maths': [99, 85, 88, 50],
    'Chemistry': [90, 65, 75, 80],
    'Physics': [85, 65, 87, 33],
    'Department': ['SCMS', 'SCMS', 'CS', 'Physics']
})
print("Original DataFrame:")
print(df)


# 1. Find all teh students with less than average marks for each subject

print("\n1. Students with less than average marks:")
print("\nPython:")
print(df[df["Python"] < df["Python"].mean()])

print("\nMaths:")
print(df[df["Maths"] < df["Maths"].mean()])

print("\nChemistry:")
print(df[df["Chemistry"] < df["Chemistry"].mean()])

print("\nPhysics:")
print(df[df["Physics"] < df["Physics"].mean()])


# 2. Get the list of students who have scored more than 80 and are in SCMS

print("\n2. Students who scored more than 80 and are in SCMS:")

result = df[(df["Python"] > 80) & (df["Department"] == "SCMS")]
print(result)


# 3. Add a new column in which all the student scoring more than 70 marks pass and other fail (use between())

df["Result"] = df["Python"].between(71, 100).map({
    True: "Pass",
    False: "Fail"
})
print("\n3. DataFrame after adding Result column:")
print(df)


# 4. list all teh student passed

print("\n4. Students who passed:")
passed_students = df[df["Result"] == "Pass"]
print(passed_students)

Original DataFrame:
     Name  Python  Maths  Chemistry  Physics Department
0  Vedant      85     99         90       85       SCMS
1  Aditya      92     85         65       65       SCMS
2  Prapti      78     88         75       87         CS
3   Saily      90     50         80       33    Physics

1. Students with less than average marks:

Python:
     Name  Python  Maths  Chemistry  Physics Department
0  Vedant      85     99         90       85       SCMS
2  Prapti      78     88         75       87         CS

Maths:
    Name  Python  Maths  Chemistry  Physics Department
3  Saily      90     50         80       33    Physics

Chemistry:
     Name  Python  Maths  Chemistry  Physics Department
1  Aditya      92     85         65       65       SCMS
2  Prapti      78     88         75       87         CS

Physics:
     Name  Python  Maths  Chemistry  Physics Department
1  Aditya      92     85         65       65       SCMS
3   Saily      90     50         80       33    Physics

2. Students who scored more than 80 and are in SCMS:
     Name  Python  Maths  Chemistry  Physics Department
0  Vedant      85     99         90       85       SCMS
1  Aditya      92     85         65       65       SCMS

3. DataFrame after adding Result column:
     Name  Python  Maths  Chemistry  Physics Department Result
0  Vedant      85     99         90       85       SCMS   Pass
1  Aditya      92     85         65       65       SCMS   Pass
2  Prapti      78     88         75       87         CS   Pass
3   Saily      90     50         80       33    Physics   Pass

4. Students who passed:
     Name  Python  Maths  Chemistry  Physics Department Result
0  Vedant      85     99         90       85       SCMS   Pass
1  Aditya      92     85         65       65       SCMS   Pass
2  Prapti      78     88         75       87         CS   Pass
3   Saily      90     50         80       33    Physics   Pass

###############################################################################

>We've been creating DataFrames ourselves.\
>But real data usually doesn't arrive as a Python dictionary.
It may come from:

experiments\
databases\
surveys\
instruments\
public datasets\
spreadsheets exported as CSV

### So lets load data using *CSV (Comma Seperated Values)*

```python

import pandas as pd

df = pd.read_csv("bmw_with_missing_data.csv")

df

In [17]:
#code here

import pandas as pd

df = pd.read_csv("bmw_with_missing_data.csv")

df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,NaN,57.6,2.0
1,6 Series,NaN,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,NaN,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,NaN,72.4,1.5
4,7 Series,2014,NaN,Automatic,39554,Diesel,160,50.4,3.0
...,...,...,...,...,...,...,...,...,...
102,ERROR_DATA,abc,xyz,Manual,def,Petrol,ghi,jkl,mno
103,DUPLICATE,2016,14000,Automatic,50000,Diesel,125,60.1,2.0
104,DUPLICATE,2016,14000,Automatic,50000,Diesel,125,60.1,2.0
105,X7,2020,45000,Automatic,5000,Petrol,NaN,42.5,3.0
106,Test Car,2025,NaN,Manual,NaN,Unknown,999,NaN,999

### Try this with the loaded df and try to understand the data?

df.head()

df.tail()

df.shape

df.columns

df.index

df.dtypes

df.info()

df.describe()

In [22]:
#code here


df.head()

df.tail()

df.shape

df.columns

df.index

df.dtypes

df.info()

df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         98 non-null     str
 1   year          87 non-null     str
 2   price         90 non-null     str
 3   transmission  93 non-null     str
 4   mileage       91 non-null     str
 5   fuelType      93 non-null     str
 6   tax           100 non-null    str
 7   mpg           93 non-null     str
 8   engineSize    106 non-null    str
dtypes: str(9)
memory usage: 7.7 KB

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
count,98,87,90,93,91,93,100,93,106
unique,21,10,63,3,90,6,14,32,7
top,1 Series,2017,14000,Automatic,50000,Diesel,145,62.8,2.0
freq,26,29,7,52,2,66,21,8,67

### <span style="color: green">To Do</span>

1. Find BMWs costing more than £20,000.
2. Cars manufactured after 2017.
3. What types of fuel exist in this dataset?
4. Find transmission using either Automatic.
5. Find cars with mileage between 20,000 and 50,000.
6. How many different fuel types are present?
7. Which transmission type occurs most frequently?

In [23]:
#code here

# Convert numerical columns to numeric
df["year"] = pd.to_numeric(df["year"], errors="coerce")
df["price"] = pd.to_numeric(df["price"], errors="coerce")
df["mileage"] = pd.to_numeric(df["mileage"], errors="coerce")


# 1. Find BMWs costing more than £20,000
print("1. BMWs costing more than £20,000:")
print(df[df["price"] > 20000])


# 2. Cars manufactured after 2017
print("\n2. Cars manufactured after 2017:")
print(df[df["year"] > 2017])


# 3. What types of fuel exist in this dataset?
print("\n3. Types of fuel in the dataset:")
print(df["fuelType"].unique())


# 4. Find cars using Automatic transmission
print("\n4. Cars with Automatic transmission:")
print(df[df["transmission"] == "Automatic"])


# 5. Find cars with mileage between 20,000 and 50,000
print("\n5. Cars with mileage between 20,000 and 50,000:")
print(df[df["mileage"].between(20000, 50000)])


# 6. How many different fuel types are present?
print("\n6. Number of different fuel types:")
print(df["fuelType"].nunique())


# 7. Which transmission type occurs most frequently?
print("\n7. Most frequent transmission type:")
print(df["transmission"].mode().iloc[0])

1. BMWs costing more than £20,000:
         model    year    price transmission  mileage  fuelType  tax    mpg  \
1     6 Series     NaN  27000.0    Automatic  14827.0    Petrol  145   42.8
31          X4     NaN  23000.0    Automatic  34960.0    Diesel  150   54.3
33    1 Series  2017.0  20500.0    Automatic      NaN    Petrol  145   39.8
44    5 Series     NaN  23500.0    Automatic  25034.0    Diesel  200   47.9
80          X3  2016.0  21750.0    Automatic      NaN    Diesel  150   54.3
92          X3  2017.0  23000.0    Semi-Auto      NaN    Diesel  150   54.3
93          M4     NaN  29998.0    Semi-Auto  34209.0    Petrol  300   34.0
99      BMW Z4  2019.0  35000.0    Automatic  15000.0    Petrol  165   45.2
101    UNKNOWN  2020.0  25000.0          NaN   8000.0  Electric    0  200.0
105         X7  2020.0  45000.0    Automatic   5000.0    Petrol  NaN   42.5

    engineSize
1          2.0
31         2.0
33         3.0
44         2.0
80         2.0
92         2.0
93         3.0
99         2.0
101        2.0
105        3.0

2. Cars manufactured after 2017:
        model    year    price transmission  mileage  fuelType  tax    mpg  \
7    2 Series  2018.0  16250.0       Manual  10401.0    Petrol  145   52.3
26   3 Series  2019.0  17800.0    Automatic  22310.0    Diesel  NaN   64.2
39   1 Series  2018.0  14600.0          NaN   6522.0    Petrol  145   37.2
43   1 Series  2018.0  17500.0    Automatic  14037.0       NaN  145   54.3
58         X1  2018.0  18000.0       Manual      NaN    Petrol  150   51.4
71   1 Series  2018.0  11700.0       Manual      NaN    Diesel  145   53.3
88   3 Series  2018.0  19490.0          NaN  30703.0    Diesel  145   57.6
99     BMW Z4  2019.0  35000.0    Automatic  15000.0    Petrol  165   45.2
100    BMW i8  2018.0      NaN    Automatic  12500.0    Hybrid    0    NaN
101   UNKNOWN  2020.0  25000.0          NaN   8000.0  Electric    0  200.0
105        X7  2020.0  45000.0    Automatic   5000.0    Petrol  NaN   42.5
106  Test Car  2025.0      NaN       Manual      NaN   Unknown  999    NaN

    engineSize
7          2.0
26         2.0
39         1.5
43         1.5
58         1.5
71         1.5
88         2.0
99         2.0
100        1.5
101        2.0
105        3.0
106        999

3. Types of fuel in the dataset:
<StringArray>
['Diesel', 'Petrol', nan, 'Other', 'Hybrid', 'Electric', 'Unknown']
Length: 7, dtype: str

4. Cars with Automatic transmission:
         model    year    price transmission  mileage fuelType  tax    mpg  \
0     5 Series  2014.0  11200.0    Automatic  67068.0   Diesel  NaN   57.6
1     6 Series     NaN  27000.0    Automatic  14827.0   Petrol  145   42.8
3     1 Series  2017.0  12750.0    Automatic  26676.0   Diesel  NaN   72.4
4     7 Series  2014.0      NaN    Automatic  39554.0   Diesel  160   50.4
5          NaN  2016.0  14900.0    Automatic  35309.0   Diesel  125   60.1
6     5 Series  2017.0  16000.0    Automatic      NaN   Diesel  125    NaN
9     5 Series  2016.0  14250.0    Automatic  36099.0   Diesel   20   68.9
12          X3  2016.0  15500.0    Automatic  77823.0   Diesel  125   54.3
14          X3  2017.0      NaN    Automatic  19057.0   Diesel  145   54.3
16         NaN  2017.0  14250.0    Automatic  55594.0    Other  135  148.7
17    3 Series     NaN  16000.0    Automatic  45456.0   Diesel   30   64.2
18    1 Series  2017.0  15500.0    Automatic  22812.0   Diesel  NaN   68.9
19    4 Series  2014.0  14000.0    Automatic  47348.0   Diesel  125    NaN
20    1 Series  2015.0      NaN    Automatic  75124.0   Diesel   20   70.6
22    3 Series  2016.0  15100.0    Automatic      NaN   Diesel   30   64.2
24         NaN  2016.0  14300.0    Automatic  22461.0   Diesel   20   67.3
26    3 Series  2019.0  17800.0    Automatic  22310.0   Diesel  NaN   64.2
27    3 Series  2016.0      NaN    Automatic  51994.0   Diesel   30   62.8
28          X5  2016.0  19750.0    Automatic      NaN   Diesel  165   52.3
29          X3  2015.0  17400.0    Automatic  50316.0      NaN  200   47.9
30    4 Series  2017.0  16800.0    Automatic  44011.0   Diesel  150    NaN
31          X4     NaN  23000.0    Automatic  34960.0   Diesel  150   54.3
33    1 Series  2017.0  20500.0    Automatic      NaN   Petrol  145   39.8
35    2 Series  2017.0  13000.0    Automatic  61818.0      NaN    0  141.2
38          X1  2017.0  18900.0    Automatic  33514.0   Diesel  145    NaN
42          X3  2013.0      NaN    Automatic  79972.0   Diesel  200   47.1
43    1 Series  2018.0  17500.0    Automatic  14037.0      NaN  145   54.3
44    5 Series     NaN  23500.0    Automatic  25034.0   Diesel  200   47.9
45          X1  2016.0  16700.0    Automatic      NaN   Diesel  125   60.1
47    4 Series  2016.0  15500.0    Automatic  45856.0      NaN   30   65.7
51    5 Series  2014.0  11000.0    Automatic      NaN   Diesel   30   62.8
52    3 Series  2017.0  18500.0    Automatic  27139.0      NaN  160   51.4
53    1 Series     NaN  12750.0    Automatic  91563.0   Diesel  125   60.1
55          X1  2017.0      NaN    Automatic  54120.0   Diesel   30   65.7
61    1 Series     NaN  14500.0    Automatic  27245.0   Diesel  145    NaN
62    3 Series  2013.0  12750.0    Automatic  35736.0   Diesel  NaN   58.9
63          X1  2017.0      NaN    Automatic  55782.0   Diesel  145   65.7
69    5 Series  2016.0      NaN    Automatic  35474.0   Diesel  125   60.1
73    5 Series  2016.0  14400.0    Automatic  51552.0      NaN   30   62.8
78         NaN  2014.0  15000.0    Automatic  13858.0   Diesel  125   57.6
80          X3  2016.0  21750.0    Automatic      NaN   Diesel  150   54.3
81    2 Series     NaN  13900.0    Automatic  46281.0   Petrol  125    NaN
82          X1  2017.0  14000.0    Automatic  54183.0      NaN  150   65.7
83          X1  2017.0      NaN    Automatic  36701.0   Diesel   30   65.7
86    2 Series  2017.0  16000.0    Automatic      NaN    Other    0  141.2
87    5 Series     NaN  14000.0    Automatic  39235.0   Diesel   30    NaN
96          X1  2017.0  17800.0    Automatic  31238.0      NaN  145   55.4
99      BMW Z4  2019.0  35000.0    Automatic  15000.0   Petrol  165   45.2
100     BMW i8  2018.0      NaN    Automatic  12500.0   Hybrid    0    NaN
103  DUPLICATE  2016.0  14000.0    Automatic  50000.0   Diesel  125   60.1
104  DUPLICATE  2016.0  14000.0    Automatic  50000.0   Diesel  125   60.1
105         X7  2020.0  45000.0    Automatic   5000.0   Petrol  NaN   42.5

    engineSize
0          2.0
1          2.0
3          1.5
4          3.0
5          2.0
6          2.0
9          2.0
12         NaN
14         2.0
16         2.0
17         2.0
18         1.5
19         2.0
20         2.0
22         2.0
24         2.0
26         2.0
27         2.0
28         2.0
29         3.0
30         2.0
31         2.0
33         3.0
35         1.5
38         2.0
42         3.0
43         1.5
44         2.0
45         2.0
47         2.0
51         2.0
52         3.0
53         2.0
55         2.0
61         2.0
62         2.0
63         2.0
69         2.0
73         2.0
78         2.0
80         2.0
81         1.5
82         2.0
83         2.0
86         1.5
87         2.0
96         2.0
99         2.0
100        1.5
103        2.0
104        2.0
105        3.0

5. Cars with mileage between 20,000 and 50,000:
         model    year    price transmission  mileage fuelType  tax    mpg  \
3     1 Series  2017.0  12750.0    Automatic  26676.0   Diesel  NaN   72.4
4     7 Series  2014.0      NaN    Automatic  39554.0   Diesel  160   50.4
5          NaN  2016.0  14900.0    Automatic  35309.0   Diesel  125   60.1
8     4 Series  2017.0  14250.0       Manual  42668.0      NaN   30   62.8
9     5 Series  2016.0  14250.0    Automatic  36099.0   Diesel   20   68.9
11    1 Series     NaN  11800.0       Manual  29840.0   Diesel   20    NaN
17    3 Series     NaN  16000.0    Automatic  45456.0   Diesel   30   64.2
18    1 Series  2017.0  15500.0    Automatic  22812.0   Diesel  NaN   68.9
19    4 Series  2014.0  14000.0    Automatic  47348.0   Diesel  125    NaN
23    1 Series     NaN   9400.0       Manual  44498.0   Diesel    0   83.1
24         NaN  2016.0  14300.0    Automatic  22461.0   Diesel   20   67.3
25    1 Series  2016.0  11200.0       Manual  23005.0      NaN  125   53.3
26    3 Series  2019.0  17800.0    Automatic  22310.0   Diesel  NaN   64.2
30    4 Series  2017.0  16800.0    Automatic  44011.0   Diesel  150    NaN
31          X4     NaN  23000.0    Automatic  34960.0   Diesel  150   54.3
32          i3  2016.0  17100.0          NaN  25269.0    Other    0  470.8
34    1 Series     NaN  11900.0       Manual  22920.0   Petrol  145   53.3
37    1 Series  2016.0  13500.0       Manual  29226.0   Diesel  NaN   62.8
38          X1  2017.0  18900.0    Automatic  33514.0   Diesel  145    NaN
41         NaN  2016.0  11400.0       Manual  21591.0   Petrol  125   53.3
44    5 Series     NaN  23500.0    Automatic  25034.0   Diesel  200   47.9
47    4 Series  2016.0  15500.0    Automatic  45856.0      NaN   30   65.7
48    1 Series     NaN   9400.0       Manual  48858.0   Diesel    0   83.1
49    1 Series  2017.0      NaN       Manual  40399.0   Diesel  145   68.9
52    3 Series  2017.0  18500.0    Automatic  27139.0      NaN  160   51.4
54    3 Series  2014.0  14000.0       Manual  32139.0   Petrol  205    NaN
56          X1     NaN  14000.0       Manual  20925.0   Diesel  150   68.9
57    3 Series  2016.0  12750.0          NaN  30521.0   Diesel   20   68.9
60         NaN  2017.0  12700.0       Manual  21809.0   Petrol  145   53.3
61    1 Series     NaN  14500.0    Automatic  27245.0   Diesel  145    NaN
62    3 Series  2013.0  12750.0    Automatic  35736.0   Diesel  NaN   58.9
64    1 Series  2016.0  10800.0          NaN  26404.0   Petrol  125   53.3
66         NaN  2016.0  12500.0       Manual  24111.0   Petrol  145   47.1
67    3 Series  2017.0  13600.0       Manual  22763.0      NaN  145   48.7
69    5 Series  2016.0      NaN    Automatic  35474.0   Diesel  125   60.1
74    1 Series     NaN  11100.0       Manual  29508.0   Petrol  125   53.3
75    1 Series  2017.0      NaN       Manual  30865.0   Diesel  145   72.4
76    5 Series  2014.0  12400.0          NaN  46356.0   Diesel   30   62.8
79    2 Series  2017.0      NaN       Manual  33752.0   Petrol  125   52.3
81    2 Series     NaN  13900.0    Automatic  46281.0   Petrol  125    NaN
83          X1  2017.0      NaN    Automatic  36701.0   Diesel   30   65.7
84    3 Series  2017.0  13500.0          NaN  48082.0   Petrol  150   51.4
87    5 Series     NaN  14000.0    Automatic  39235.0   Diesel   30    NaN
88    3 Series  2018.0  19490.0          NaN  30703.0   Diesel  145   57.6
89    1 Series  2015.0  15499.0    Semi-Auto  20000.0      NaN  125   60.1
90    2 Series     NaN  13000.0    Semi-Auto  34971.0   Diesel  150   72.4
91    1 Series  2014.0      NaN    Semi-Auto  44900.0   Diesel   30   64.2
93          M4     NaN  29998.0    Semi-Auto  34209.0   Petrol  300   34.0
96          X1  2017.0  17800.0    Automatic  31238.0      NaN  145   55.4
97    3 Series     NaN  13100.0       Manual  37204.0   Diesel   30   64.2
98    1 Series  2017.0      NaN       Manual  26265.0   Diesel    0   83.1
103  DUPLICATE  2016.0  14000.0    Automatic  50000.0   Diesel  125   60.1
104  DUPLICATE  2016.0  14000.0    Automatic  50000.0   Diesel  125   60.1

    engineSize
3          1.5
4          3.0
5          2.0
8          2.0
9          2.0
11         2.0
17         2.0
18         1.5
19         2.0
23         1.5
24         2.0
25         1.5
26         2.0
30         2.0
31         2.0
32         0.6
34         1.5
37         2.0
38         2.0
41         1.5
44         2.0
47         2.0
48         1.5
49         2.0
52         3.0
54         2.0
56         2.0
57         2.0
60         1.5
61         2.0
62         2.0
64         1.5
66         1.6
67         2.0
69         2.0
74         1.5
75         1.5
76         2.0
79         1.5
81         1.5
83         2.0
84         2.0
87         2.0
88         2.0
89         2.0
90         1.5
91         2.0
93         3.0
96         2.0
97         2.0
98         1.5
103        2.0
104        2.0

6. Number of different fuel types:
6

7. Most frequent transmission type:
Automatic

### Why do we need sorting?

Imagine our dataset contains thousands of cars.

If we want to answer questions such as:

Which cars are the most expensive?\
Which cars are the cheapest?\
Which cars have the highest mileage?\
Which cars are the newest?

Looking at the DataFrame row by row isn't very useful.

We need a way to rearrange the rows according to a particular column.

Pandas provides:

```python 
sort_values()

df.sort_values("column_name")

lets try sorting based on the price

```python 
df.sort_values("price")

if you want to sort in decending order

df.sort_values("price", ascending=False)

In [29]:
#code here

print(df.sort_values("price"))

print()
 
df.sort_values("price")

print()

df.sort_values("price", ascending=False)

          model    year    price transmission  mileage fuelType  tax   mpg  \
95          NaN  2015.0   7948.0       Manual  74375.0   Diesel   30   NaN
23     1 Series     NaN   9400.0       Manual  44498.0   Diesel    0  83.1
48     1 Series     NaN   9400.0       Manual  48858.0   Diesel    0  83.1
13     2 Series  2015.0  10500.0       Manual      NaN   Diesel   20  68.9
64     1 Series  2016.0  10800.0          NaN  26404.0   Petrol  125  53.3
..          ...     ...      ...          ...      ...      ...  ...   ...
91     1 Series  2014.0      NaN    Semi-Auto  44900.0   Diesel   30  64.2
98     1 Series  2017.0      NaN       Manual  26265.0   Diesel    0  83.1
100      BMW i8  2018.0      NaN    Automatic  12500.0   Hybrid    0   NaN
102  ERROR_DATA     NaN      NaN       Manual      NaN   Petrol  ghi   jkl
106    Test Car  2025.0      NaN       Manual      NaN  Unknown  999   NaN

    engineSize
95         2.0
23         1.5
48         1.5
13         2.0
64         1.5
..         ...
91         2.0
98         1.5
100        1.5
102        mno
106        999

[107 rows x 9 columns]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
105,X7,2020.0,45000.0,Automatic,5000.0,Petrol,NaN,42.5,3.0
99,BMW Z4,2019.0,35000.0,Automatic,15000.0,Petrol,165,45.2,2.0
93,M4,NaN,29998.0,Semi-Auto,34209.0,Petrol,300,34.0,3.0
1,6 Series,NaN,27000.0,Automatic,14827.0,Petrol,145,42.8,2.0
101,UNKNOWN,2020.0,25000.0,NaN,8000.0,Electric,0,200.0,2.0
...,...,...,...,...,...,...,...,...,...
91,1 Series,2014.0,NaN,Semi-Auto,44900.0,Diesel,30,64.2,2.0
98,1 Series,2017.0,NaN,Manual,26265.0,Diesel,0,83.1,1.5
100,BMW i8,2018.0,NaN,Automatic,12500.0,Hybrid,0,NaN,1.5
102,ERROR_DATA,NaN,NaN,Manual,NaN,Petrol,ghi,jkl,mno
106,Test Car,2025.0,NaN,Manual,NaN,Unknown,999,NaN,999

### <span style="color: green"> To Do</span>
1. Which cars have the highest mileage?
2. Which cars have the newest model year?
3. Which cars have the largest engine?

In [31]:
#code here
# 1. Which cars have the highest mileage?
print("1. Cars with highest mileage:")
print(df.sort_values("mileage", ascending=False))


# 2. Which cars have the newest model year?
print("\n2. Cars with newest model year:")
print(df.sort_values("year", ascending=False))


# 3. Which cars have the largest engine?
print("\n3. Cars with largest engine:")
print(df.sort_values("engineSize", ascending=False))

1. Cars with highest mileage:
          model    year    price transmission  mileage fuelType  tax    mpg  \
53     1 Series     NaN  12750.0    Automatic  91563.0   Diesel  125   60.1
42           X3  2013.0      NaN    Automatic  79972.0   Diesel  200   47.1
21     3 Series  2015.0  12600.0          NaN  78957.0   Diesel   30   62.8
12           X3  2016.0  15500.0    Automatic  77823.0   Diesel  125   54.3
85           X1     NaN  12150.0       Manual  77482.0   Diesel   20   68.9
..          ...     ...      ...          ...      ...      ...  ...    ...
80           X3  2016.0  21750.0    Automatic      NaN   Diesel  150   54.3
86     2 Series  2017.0  16000.0    Automatic      NaN    Other    0  141.2
92           X3  2017.0  23000.0    Semi-Auto      NaN   Diesel  150   54.3
102  ERROR_DATA     NaN      NaN       Manual      NaN   Petrol  ghi    jkl
106    Test Car  2025.0      NaN       Manual      NaN  Unknown  999    NaN

    engineSize
53         2.0
42         3.0
21         2.0
12         NaN
85         2.0
..         ...
80         2.0
86         1.5
92         2.0
102        mno
106        999

[107 rows x 9 columns]

2. Cars with newest model year:
          model    year    price transmission  mileage  fuelType  tax    mpg  \
106    Test Car  2025.0      NaN       Manual      NaN   Unknown  999    NaN
101     UNKNOWN  2020.0  25000.0          NaN   8000.0  Electric    0  200.0
105          X7  2020.0  45000.0    Automatic   5000.0    Petrol  NaN   42.5
26     3 Series  2019.0  17800.0    Automatic  22310.0    Diesel  NaN   64.2
99       BMW Z4  2019.0  35000.0    Automatic  15000.0    Petrol  165   45.2
..          ...     ...      ...          ...      ...       ...  ...    ...
87     5 Series     NaN  14000.0    Automatic  39235.0    Diesel   30    NaN
90     2 Series     NaN  13000.0    Semi-Auto  34971.0    Diesel  150   72.4
93           M4     NaN  29998.0    Semi-Auto  34209.0    Petrol  300   34.0
97     3 Series     NaN  13100.0       Manual  37204.0    Diesel   30   64.2
102  ERROR_DATA     NaN      NaN       Manual      NaN    Petrol  ghi    jkl

    engineSize
106        999
101        2.0
105        3.0
26         2.0
99         2.0
..         ...
87         2.0
90         1.5
93         3.0
97         2.0
102        mno

[107 rows x 9 columns]

3. Cars with largest engine:
          model    year    price transmission  mileage fuelType  tax    mpg  \
102  ERROR_DATA     NaN      NaN       Manual      NaN   Petrol  ghi    jkl
106    Test Car  2025.0      NaN       Manual      NaN  Unknown  999    NaN
29           X3  2015.0  17400.0    Automatic  50316.0      NaN  200   47.9
33     1 Series  2017.0  20500.0    Automatic      NaN   Petrol  145   39.8
42           X3  2013.0      NaN    Automatic  79972.0   Diesel  200   47.1
..          ...     ...      ...          ...      ...      ...  ...    ...
79     2 Series  2017.0      NaN       Manual  33752.0   Petrol  125   52.3
81     2 Series     NaN  13900.0    Automatic  46281.0   Petrol  125    NaN
25     1 Series  2016.0  11200.0       Manual  23005.0      NaN  125   53.3
32           i3  2016.0  17100.0          NaN  25269.0    Other    0  470.8
12           X3  2016.0  15500.0    Automatic  77823.0   Diesel  125   54.3

    engineSize
102        mno
106        999
29         3.0
33         3.0
42         3.0
..         ...
79         1.5
81         1.5
25         1.5
32         0.6
12         NaN

[107 rows x 9 columns]

### <span style="color:cyan">Think</span>

Did the original df change?

### Sorting by Multiple Columns
Sometimes one column isn't enough.

Suppose two cars have the same price.

We may want to sort those cars further by their mileage.

Pandas allows us to provide a list of columns.

```python
df.sort_values(
    ["price", "mileage"],
    ascending=[False, True]
)

This means:

Sort by price from highest to lowest.
If two cars have the same price, sort those cars by mileage from lowest to highest.

In [32]:
#code here
df.sort_values(
    ["price", "mileage"],
    ascending=[False, True]
)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
105,X7,2020.0,45000.0,Automatic,5000.0,Petrol,NaN,42.5,3.0
99,BMW Z4,2019.0,35000.0,Automatic,15000.0,Petrol,165,45.2,2.0
93,M4,NaN,29998.0,Semi-Auto,34209.0,Petrol,300,34.0,3.0
1,6 Series,NaN,27000.0,Automatic,14827.0,Petrol,145,42.8,2.0
101,UNKNOWN,2020.0,25000.0,NaN,8000.0,Electric,0,200.0,2.0
...,...,...,...,...,...,...,...,...,...
36,3 Series,2015.0,NaN,Manual,59634.0,Diesel,125,61.4,2.0
20,1 Series,2015.0,NaN,Automatic,75124.0,Diesel,20,70.6,2.0
42,X3,2013.0,NaN,Automatic,79972.0,Diesel,200,47.1,3.0
102,ERROR_DATA,NaN,NaN,Manual,NaN,Petrol,ghi,jkl,mno
106,Test Car,2025.0,NaN,Manual,NaN,Unknown,999,NaN,999

### <span style="color:cyan">Think</span>

What do you expect this to do?
```python
df.sort_values(
    ["fuelType", "price"]
)

In [33]:
#code here


df.sort_values(
    ["fuelType", "price"]
)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
95,NaN,2015.0,7948.0,Manual,74375.0,Diesel,30,NaN,2.0
23,1 Series,NaN,9400.0,Manual,44498.0,Diesel,0,83.1,1.5
48,1 Series,NaN,9400.0,Manual,48858.0,Diesel,0,83.1,1.5
13,2 Series,2015.0,10500.0,Manual,NaN,Diesel,20,68.9,2.0
72,2 Series,NaN,10900.0,Manual,62021.0,Diesel,145,NaN,2.0
...,...,...,...,...,...,...,...,...,...
15,3 Series,2017.0,16500.0,Manual,16570.0,NaN,125,58.9,2.0
29,X3,2015.0,17400.0,Automatic,50316.0,NaN,200,47.9,3.0
43,1 Series,2018.0,17500.0,Automatic,14037.0,NaN,145,54.3,1.5
96,X1,2017.0,17800.0,Automatic,31238.0,NaN,145,55.4,2.0
52,3 Series,2017.0,18500.0,Automatic,27139.0,NaN,160,51.4,3.0

### Basic Statistics

We've sorted the data.

Now let's start asking numerical questions.

For example:

What is the average price of the cars in our dataset?

We could manually add all the prices and divide by the number of cars.

But that's exactly the kind of repetitive calculation that Pandas should handle for us.

Pandas provides common statistical operations directly on Series.

```python 
df["price"].min()
df["price"].max()
df["price"].median()
df["price"].std()

In [36]:
#code here

print("Minimum price:", df["price"].min())


print("Maximum price:", df["price"].max())


print("Median price:", df["price"].median())



df["price"].std()

Minimum price: 7948.0
Maximum price: 45000.0
Median price: 14250.0

np.float64(5372.571445421582)

### Combining Statistics
Sometimes we don't want to run five separate commands:
>mean()\
>min()\
>max()\
>median()\
>std()

Pandas provides:
>agg()

```python
df["engineSize"].agg(["count", "mean", "min", "max", "median", "std"])

In [41]:
#code here

df["engineSize"].dtype

df["engineSize"] = pd.to_numeric(df["engineSize"], errors="coerce")

df["engineSize"].agg(["count", "mean", "min", "max", "median", "std"])

count     105.000000
mean       11.440000
min         0.600000
max       999.000000
median      2.000000
std        97.303534
Name: engineSize, dtype: float64

```python
df["engineSize"].agg(["count", "mean", "min", "max", "median", "std"])

We have actually encountered describe() earlier.

Now we can understand what it is doing at a conceptual level:

describe() provides a statistical summary of numerical data.

In [43]:
#code here


df["engineSize"].agg(["count", "mean", "min", "max", "median", "std"])

count     105.000000
mean       11.440000
min         0.600000
max       999.000000
median      2.000000
std        97.303534
Name: engineSize, dtype: float64

### Missing Data in Real Datasets

In real-world data, it's common to encounter missing or incomplete values.

Missing data can occur due to:
- Data collection errors
- Incomplete surveys
- Equipment failures
- Data entry mistakes
- Intentional omissions

Pandas represents missing data as:
- `NaN` (Not a Number) for numerical data
- `None` for object/string data

Missing data can cause problems in analysis and calculations, so we need to handle it properly.

In [44]:
# Let's create a DataFrame with missing data to explore
import pandas as pd
import numpy as np

# Create sample data with missing values
students_with_missing = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Python': [85, np.nan, 78, 90, np.nan],
    'Maths': [99, 85, np.nan, 50, 88],
    'Chemistry': [90, np.nan, 75, np.nan, 92],
    'Physics': [85, 65, 87, 33, np.nan]
})

print("DataFrame with Missing Values:")
print(students_with_missing)
print("\nData types:")
print(students_with_missing.dtypes)

DataFrame with Missing Values:
      Name  Python  Maths  Chemistry  Physics
0    Alice    85.0   99.0       90.0     85.0
1      Bob     NaN   85.0        NaN     65.0
2  Charlie    78.0    NaN       75.0     87.0
3    Diana    90.0   50.0        NaN     33.0
4      Eve     NaN   88.0       92.0      NaN

Data types:
Name             str
Python       float64
Maths        float64
Chemistry    float64
Physics      float64
dtype: object

### Detecting Missing Data

Pandas provides methods to identify where missing values are:

- `isnull()` or `isna()` - Returns True where values are missing
- `notnull()` or `notna()` - Returns True where values are NOT missing
- `info()` - Shows count of non-null values for each column

Try these commands:
```python
students_with_missing.isnull()
students_with_missing.isna()
students_with_missing.isnull().sum()  # Count missing values per column
students_with_missing.info()
```

In [ ]:
# code here
# Test isnull(), isna(), and info() methods to identify missing data

students_with_missing.isnull()
students_with_missing.isna()
students_with_missing.isnull().sum()  
students_with_missing.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      str
 1   Python     3 non-null      float64
 2   Maths      4 non-null      float64
 3   Chemistry  3 non-null      float64
 4   Physics    4 non-null      float64
dtypes: float64(4), str(1)
memory usage: 332.0 bytes

### Handling Missing Data: dropna()

`dropna()` removes rows or columns containing missing values.

**Strategies:**
- Drop entire rows with ANY missing value
- Drop entire columns with ANY missing value
- Drop rows where ALL values are missing
- Drop columns where ALL values are missing

**Syntax:**
```python
df.dropna()                           # Remove rows with any NaN
df.dropna(axis=1)                     # Remove columns with any NaN
df.dropna(how='all')                  # Remove rows where ALL values are NaN
df.dropna(subset=['column_name'])     # Remove rows where specific column has NaN
df.dropna(thresh=3)                   # Keep rows with at least 3 non-null values
```

**Warning:** Dropping rows/columns removes data! Use with caution.

In [48]:
# code here
# Try different dropna() strategies:
# 1. Remove rows with ANY missing value
students_with_missing.dropna()

# 2. Remove columns with ANY missing value
students_with_missing.dropna(axis=1)

# 3. Remove rows where ALL values are missing
students_with_missing.dropna(how="all")

# 4. Remove rows where specific columns have NaN
students_with_missing.dropna(subset=["Python", "Maths"])

    Name  Python  Maths  Chemistry  Physics
0  Alice    85.0   99.0       90.0     85.0
3  Diana    90.0   50.0        NaN     33.0

### Handling Missing Data: fillna()

`fillna()` replaces missing values with specified values instead of removing data.

This is often better than dropping data because it preserves row/column count.

**Methods:**
```python
df.fillna(0)                          # Replace all NaN with 0
df.fillna('Unknown')                  # Replace with a specific value
df.fillna(method='ffill')             # Forward fill: use previous value
df.fillna(method='bfill')             # Backward fill: use next value
df['column'].fillna(df['column'].mean())  # Fill with mean/median/mode
df.fillna({'col1': 0, 'col2': 'N/A'}) # Fill different columns differently
```

**Forward Fill (ffill):** Propagates the last known value forward
**Backward Fill (bfill):** Propagates the next known value backward

In [57]:
# code here
# Try different fillna() strategies:

# 1. Fill missing values with a constant value
students_with_missing.fillna(0)

# 2. Fill missing values with the mean of each column
students_with_missing.fillna(
    students_with_missing.select_dtypes(include='number').mean()
)
# 3. Use forward fill (ffill)
students_with_missing.ffill()

# 4. Fill different columns with different values
students_with_missing.fillna({
    'Python': 0,
    'Maths': 50,
    'Chemistry': 0,
    'Physics': 40
})

# 5. Use backward fill (bfill)
students_with_missing.bfill()

      Name  Python  Maths  Chemistry  Physics
0    Alice    85.0   99.0       90.0     85.0
1      Bob    78.0   85.0       75.0     65.0
2  Charlie    78.0   50.0       75.0     87.0
3    Diana    90.0   50.0       92.0     33.0
4      Eve     NaN   88.0       92.0      NaN

### Grouping Data with groupby()

`groupby()` splits data into groups based on one or more columns, then applies operations to each group.

This is powerful for answering questions like:
- "What is the average score per department?"
- "How many students are in each department?"
- "What is the total sales per region?"

**Basic Syntax:**
```python
df.groupby('column').operation()
```

**Common Operations:**
```python
df.groupby('Department').mean()       # Average for each group
df.groupby('Department').sum()        # Sum for each group
df.groupby('Department').count()      # Count of rows in each group
df.groupby('Department').min()        # Minimum value in each group
df.groupby('Department').max()        # Maximum value in each group
df.groupby('Department').agg(['mean', 'sum', 'count'])  # Multiple operations
```

**Grouping by Multiple Columns:**
```python
df.groupby(['Department', 'Gender']).mean()  # Nested grouping
```

In [58]:
# Let's create a fresh DataFrame to practice groupby()
# First, let's use our original students DataFrame with the Department column

# Quick refresh - create the students DataFrame
df_students = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Python': [85, 92, 78, 90],
    'Maths': [99, 85, 88, 50],
    'Chemistry': [90, 65, 75, 80],
    'Physics': [85, 65, 87, 33],
    'Department': ['SCMS', 'SCMS', 'CS', 'Physics']
})

print(df_students)

      Name  Python  Maths  Chemistry  Physics Department
0    Alice      85     99         90       85       SCMS
1      Bob      92     85         65       65       SCMS
2  Charlie      78     88         75       87         CS
3    Diana      90     50         80       33    Physics

In [59]:
# code here
# Try these groupby() operations:
# 1. Group by Department and calculate mean marks
print("1. Mean marks by Department:")
print(df_students.groupby('Department')[['Python', 'Maths', 'Chemistry', 'Physics']].mean())


# 2. Group by Department and calculate sum of marks
print("\n2. Sum of marks by Department:")
print(df_students.groupby('Department')[['Python', 'Maths', 'Chemistry', 'Physics']].sum())


# 3. Group by Department and count students
print("\n3. Number of students in each Department:")
print(df_students.groupby('Department').size())


# 4. Find the department with the highest average Python score
python_mean = df_students.groupby('Department')['Python'].mean()
highest_python_department = python_mean.idxmax()

print("\n4. Department with the highest average Python score:")
print(highest_python_department)
print("Average Python score:", python_mean.max())


# 5. Use agg() to get multiple statistics at once
print("\n5. Multiple statistics by Department:")
print(df_students.groupby('Department')[['Python', 'Maths', 'Chemistry', 'Physics']].agg(['mean', 'sum', 'count']))

1. Mean marks by Department:
            Python  Maths  Chemistry  Physics
Department
CS            78.0   88.0       75.0     87.0
Physics       90.0   50.0       80.0     33.0
SCMS          88.5   92.0       77.5     75.0

2. Sum of marks by Department:
            Python  Maths  Chemistry  Physics
Department
CS              78     88         75       87
Physics         90     50         80       33
SCMS           177    184        155      150

3. Number of students in each Department:
Department
CS         1
Physics    1
SCMS       2
dtype: int64

4. Department with the highest average Python score:
Physics
Average Python score: 90.0

5. Multiple statistics by Department:
           Python            Maths            Chemistry            Physics  \
             mean  sum count  mean  sum count      mean  sum count    mean
Department
CS           78.0   78     1  88.0   88     1      75.0   75     1    87.0
Physics      90.0   90     1  50.0   50     1      80.0   80     1    33.0
SCMS         88.5  177     2  92.0  184     2      77.5  155     2    75.0


            sum count
Department
CS           87     1
Physics      33     1
SCMS        150     2

### <span style="color: green">To Do - Practical Exercises</span>

**Using the BMW dataset (bmw_with_missing_data.csv):**

1. **Missing Data Exploration:**
   - Load the BMW dataset
   - Identify which columns have missing values using `isnull()` and `sum()`
   - Count total missing values in the dataset

2. **Using dropna():**
   - Remove all rows with any missing values
   - Remove only rows where the 'price' column is missing
   - Compare the original dataset size with the cleaned dataset

3. **Using fillna():**
   - Fill missing values in 'mileage' with the median
   - Fill missing values in 'fuelType' with 'Unknown'
   - Fill missing values in 'engineSize' with the mean
   - Display the resulting DataFrame

4. **Using groupby():**
   - Group by 'fuelType' and calculate average price
   - Group by 'transmission' and calculate average mileage
   - Group by 'fuelType' and find the count of cars
   - Use agg() to get mean, min, and max price by fuel type

In [65]:
# code here
# Solve all the practical exercises above
# Work through each task step by step


# 1. Missing Data Exploration

# Load the BMW dataset
df_bmw = pd.read_csv("bmw_with_missing_data.csv")

# Display the BMW dataset
print("BMW Dataset:")
print(df_bmw)

# Identify columns having missing values
print("\nMissing values in each column:")
print(df_bmw.isnull().sum())

# Count total missing values in the dataset
print("\nTotal missing values in the dataset:")
print(df_bmw.isnull().sum().sum())

BMW Dataset:
          model  year  price transmission mileage fuelType  tax   mpg  \
0      5 Series  2014  11200    Automatic   67068   Diesel  NaN  57.6
1      6 Series   NaN  27000    Automatic   14827   Petrol  145  42.8
2      5 Series  2016  16000          NaN   62794   Diesel  160  51.4
3      1 Series  2017  12750    Automatic   26676   Diesel  NaN  72.4
4      7 Series  2014    NaN    Automatic   39554   Diesel  160  50.4
..          ...   ...    ...          ...     ...      ...  ...   ...
102  ERROR_DATA   abc    xyz       Manual     def   Petrol  ghi   jkl
103   DUPLICATE  2016  14000    Automatic   50000   Diesel  125  60.1
104   DUPLICATE  2016  14000    Automatic   50000   Diesel  125  60.1
105          X7  2020  45000    Automatic    5000   Petrol  NaN  42.5
106    Test Car  2025    NaN       Manual     NaN  Unknown  999   NaN

    engineSize
0          2.0
1          2.0
2          3.0
3          1.5
4          3.0
..         ...
102        mno
103        2.0
104        2.0
105        3.0
106        999

[107 rows x 9 columns]

Missing values in each column:
model            9
year            20
price           17
transmission    14
mileage         16
fuelType        14
tax              7
mpg             14
engineSize       1
dtype: int64

Total missing values in the dataset:
112

In [66]:
# 2. Using dropna()

# Display original dataset size
print("Original dataset size:", df_bmw.shape)

# Remove all rows with any missing values
df_no_missing = df_bmw.dropna()

# Display cleaned dataset size
print("\nDataset after removing rows with any missing values:")
print(df_no_missing.shape)

# Remove only rows where the 'price' column is missing
df_price_clean = df_bmw.dropna(subset=['price'])

# Display dataset size after removing rows with missing price
print("\nDataset after removing rows where price is missing:")
print(df_price_clean.shape)

# Compare the original dataset size with the cleaned dataset
print("\nOriginal dataset rows:", len(df_bmw))
print("Rows after removing any missing value:", len(df_no_missing))
print("Rows after removing missing price:", len(df_price_clean))

Original dataset size: (107, 9)

Dataset after removing rows with any missing values:
(6, 9)

Dataset after removing rows where price is missing:
(90, 9)

Original dataset rows: 107
Rows after removing any missing value: 6
Rows after removing missing price: 90

In [67]:
# 3. Using fillna()

# Create a copy so that the original dataset is not changed
df_filled = df_bmw.copy()

# Convert numeric columns to numeric datatype
# Invalid values such as 'def' and 'mno' become NaN
df_filled['mileage'] = pd.to_numeric(df_filled['mileage'], errors='coerce')
df_filled['engineSize'] = pd.to_numeric(df_filled['engineSize'], errors='coerce')

# Fill missing values in 'mileage' with the median
df_filled['mileage'] = df_filled['mileage'].fillna(
    df_filled['mileage'].median()
)

# Fill missing values in 'fuelType' with 'Unknown'
df_filled['fuelType'] = df_filled['fuelType'].fillna('Unknown')

# Fill missing values in 'engineSize' with the mean
df_filled['engineSize'] = df_filled['engineSize'].fillna(
    df_filled['engineSize'].mean()
)

# Display the resulting DataFrame
print("DataFrame after filling missing values:")
print(df_filled)

DataFrame after filling missing values:
          model  year  price transmission  mileage fuelType  tax   mpg  \
0      5 Series  2014  11200    Automatic  67068.0   Diesel  NaN  57.6
1      6 Series   NaN  27000    Automatic  14827.0   Petrol  145  42.8
2      5 Series  2016  16000          NaN  62794.0   Diesel  160  51.4
3      1 Series  2017  12750    Automatic  26676.0   Diesel  NaN  72.4
4      7 Series  2014    NaN    Automatic  39554.0   Diesel  160  50.4
..          ...   ...    ...          ...      ...      ...  ...   ...
102  ERROR_DATA   abc    xyz       Manual  34584.5   Petrol  ghi   jkl
103   DUPLICATE  2016  14000    Automatic  50000.0   Diesel  125  60.1
104   DUPLICATE  2016  14000    Automatic  50000.0   Diesel  125  60.1
105          X7  2020  45000    Automatic   5000.0   Petrol  NaN  42.5
106    Test Car  2025    NaN       Manual  34584.5  Unknown  999   NaN

     engineSize
0          2.00
1          2.00
2          3.00
3          1.50
4          3.00
..          ...
102       11.44
103        2.00
104        2.00
105        3.00
106      999.00

[107 rows x 9 columns]

In [68]:
# 4. Using groupby()

# Convert numeric columns to numeric datatype
# Invalid values such as 'xyz' and 'def' become NaN
df_bmw['price'] = pd.to_numeric(df_bmw['price'], errors='coerce')
df_bmw['mileage'] = pd.to_numeric(df_bmw['mileage'], errors='coerce')


# Group by 'fuelType' and calculate average price
print("Average price by fuel type:")
print(df_bmw.groupby('fuelType')['price'].mean())


# Group by 'transmission' and calculate average mileage
print("\nAverage mileage by transmission:")
print(df_bmw.groupby('transmission')['mileage'].mean())


# Group by 'fuelType' and find the count of cars
print("\nCount of cars by fuel type:")
print(df_bmw.groupby('fuelType').size())


# Use agg() to get mean, min, and max price by fuel type
print("\nMean, minimum, and maximum price by fuel type:")
print(
    df_bmw.groupby('fuelType')['price'].agg(
        ['mean', 'min', 'max']
    )
)

Average price by fuel type:
fuelType
Diesel      14601.653846
Electric    25000.000000
Hybrid               NaN
Other       15783.333333
Petrol      18260.421053
Unknown              NaN
Name: price, dtype: float64

Average mileage by transmission:
transmission
Automatic    40491.75
Manual       33183.25
Semi-Auto    33520.00
Name: mileage, dtype: float64

Count of cars by fuel type:
fuelType
Diesel      66
Electric     1
Hybrid       1
Other        3
Petrol      21
Unknown      1
dtype: int64

Mean, minimum, and maximum price by fuel type:
                  mean      min      max
fuelType
Diesel    14601.653846   7948.0  23500.0
Electric  25000.000000  25000.0  25000.0
Hybrid             NaN      NaN      NaN
Other     15783.333333  14250.0  17100.0
Petrol    18260.421053  10800.0  45000.0
Unknown            NaN      NaN      NaN